name: Build and Deploy Code

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs: 
  job1: 
    runs-on: ubuntu-latest    #  specify the Operating System
    steps:
      - name: Pulling git  repo 
        uses: actions/checkout@v2 
      - name: say hi to Salih
        run: echo "Hello Salih !"

      