name: Build and Deploy Code

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs: 
  job1: 
    runs-on: ubuntu-latest    #  specify the Operating System
    steps:
      - name: Pulling git  repo 
        uses: actions/checkout@v2 
      - name: say hi to Salih
        run: echo "Hello Salih !"
      - name: Set up PYTHON
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt 
            
      